import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";  // Make sure to use /react

const newsapiHeader = {
  'x-rapidapi-key': '584cceb2a3msh2a45aebf78a8b5ap1f311ajsn84e757754edd',
  'x-rapidapi-host': 'bing-news-search1.p.rapidapi.com',
  'X-BingApis-SDK': 'true',
};

const baseUrl = "https://bing-news-search1.p.rapidapi.com";

const createRequest = (url) => ({ url, headers: newsapiHeader });

export const cryptoNewsApi = createApi({
  reducerPath: 'cryptoNewsApi',
  baseQuery: fetchBaseQuery({ baseUrl }),
  endpoints: (builder) => ({
    getCryptoNews: builder.query({
      query: ({ newsCategory, count }) => 
        createRequest(`/news/search?q=${newsCategory}&safeSearch=Off&textFormat=Raw&freshness=Day&count=${count}`),
    }),
  }),
});

// Export the hook generated by createApi
export const { useGetCryptoNewsQuery } = cryptoNewsApi;
